/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "bg-primary/20",
    "bg-secondary/20",
    "bg-accent/20",
    "bg-info/20",
    "bg-success/20",
    "bg-warning/20",
    "bg-error/20",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        colog: {
          "primary": "#D2A52B",
          "primary-content": "#201B12",
          "secondary": "#29251F",
          "secondary-content": "#FFF9EC",
          "accent": "#E88A35",
          "accent-content": "#201B12",
          "neutral": "#332E27",
          "neutral-content": "#FFF9EC",
          "base-100": "#FFFDF6",
          "base-200": "#F6EFDF",
          "base-300": "#E9DFC9",
          "base-content": "#252019",
          "info": "#5B8DB8",
          "info-content": "#F8FBFF",
          "success": "#78A65A",
          "success-content": "#172111",
          "warning": "#E89B38",
          "warning-content": "#261807",
          "error": "#D95C4E",
          "error-content": "#FFF8F5",
          "--rounded-box": "1.35rem",
          "--rounded-btn": "0.85rem",
          "--rounded-badge": "9999px",
          "--animation-btn": "0.18s",
          "--btn-text-case": "none",
          "--btn-focus-scale": "0.98",
        },
      },
      {
        "colog-dark": {
          "primary": "#E0B330",
          "primary-content": "#211B0D",
          "secondary": "#F6EEDC",
          "secondary-content": "#272119",
          "accent": "#E4A052",
          "accent-content": "#261909",
          "neutral": "#3A332A",
          "neutral-content": "#FFF9EC",
          "base-100": "#24201B",
          "base-200": "#1B1814",
          "base-300": "#332D25",
          "base-content": "#F8F1E2",
          "info": "#78A8D1",
          "info-content": "#101B26",
          "success": "#96BE72",
          "success-content": "#15200E",
          "warning": "#EEAD4D",
          "warning-content": "#291A08",
          "error": "#EF8275",
          "error-content": "#30110D",
          "--rounded-box": "1.35rem",
          "--rounded-btn": "0.85rem",
          "--rounded-badge": "9999px",
          "--animation-btn": "0.18s",
          "--btn-text-case": "none",
          "--btn-focus-scale": "0.98",
        },
      },
    ],
  },
}
